#pragma once

#include "7BitEncoding.h"
#include "BufferIO.h"
#include "Utils.h"

#include "OPL/BufferedOPLDevice.h"
#include "OPL/OPLDeviceBase.h"
#include "OPL/OPLReadWriteDeviceBase.h"
#include "OPL/OPLRegisterSet.h"
#include "OPL/OPLTone.h"
#include "OPL/OPLUtils.h"

#include "OPM/BufferedOPMDevice.h"
#include "OPM/OPMDeviceBase.h"
#include "OPM/OPMRegisterSet.h"
#include "OPM/OPMTone.h"
#include "OPM/OPMUtils.h"

#include "SD1/SD1DeviceBase.h"
#include "SD1/SD1OPLAdaptor.h"
#include "SD1/SD1Tone.h"
#include "SD1/SD1Utils.h"

#include "MIDI/BasicVoiceAllocator.h"
#include "MIDI/GlobalParams.h"
#include "MIDI/IMIDIDriver.h"
#include "MIDI/INoteManager.h"
#include "MIDI/IToneGenerator.h"
#include "MIDI/IVoiceAllocator.h"
#include "MIDI/LFO.h"
#include "MIDI/MIDICommon.h"
#include "MIDI/MIDIDriver.h"
#include "MIDI/MIDIParser.h"
#include "MIDI/MonoNoteManager.h"
#include "MIDI/ParamInfo.h"
#include "MIDI/Patch.h"
#include "MIDI/PatchManagerBase.h"
#include "MIDI/PatchParams.h"
#include "MIDI/PatchSerialization.h"
#include "MIDI/PolyNoteManager.h"
#include "MIDI/RAMPatchManager.h"
#include "MIDI/SysEx.h"
#include "MIDI/TimeSource.h"
#include "MIDI/ToneController.h"
#include "MIDI/VoiceStatus.h"

#include "MIDI/OPL/DefaultOPLPatchManager.h"
#include "MIDI/OPL/OPL2MIDISystem.h"
#include "MIDI/OPL/OPL2VoiceAllocator.h"
#include "MIDI/OPL/OPL3MIDISystem.h"
#include "MIDI/OPL/OPL3VoiceAllocator.h"
#include "MIDI/OPL/OPLGMPatchData.h"
#include "MIDI/OPL/OPLParamInfo.h"
#include "MIDI/OPL/OPLToneGenerator.h"

#include "MIDI/OPM/OPMMIDISystem.h"
#include "MIDI/OPM/OPMParamInfo.h"
#include "MIDI/OPM/OPMToneGenerator.h"

#include "MIDI/SD1/DefaultSD1PatchManager.h"
#include "MIDI/SD1/OPLSD1MIDISystem.h"
#include "MIDI/SD1/OPLSD1ToneGenerator.h"
#include "MIDI/SD1/SD1MIDISystem.h"
#include "MIDI/SD1/SD1ParamInfo.h"
#include "MIDI/SD1/SD1Patches.h"
#include "MIDI/SD1/SD1ToneGenerator.h"
